### ISSUE TITLE
Modularity in the Program

### ISSUE THREAD

**Issue by ananya12k** [soravkumarsharma/ATM-Project-for-Beginners#11]
The program consists of only function which is not good from future perspective. It should have classes that will have the functions. The main function will be small.

**Comment by Nalakajayanath** [comment]
Hi @soravkumarsharma,

I would like to do this enhancement. Can you assign this to me?

**Comment by ananya12k** [comment]
> Hi @soravkumarsharma,
> 
> I would like to do this enhancement. Can you assign this to me?

I would like to collaborate with you for this

**Comment by Nalakajayanath** [comment]
Hi @ananya12k,

Sure. But, I'm new to github. How can we do this collaboratively? Any idea?

**Comment by ananya12k** [comment]
> Hi @ananya12k,
> 
> Sure. But, I'm new to github. How can we do this collaboratively? Any idea?


We can do the if the repository owner assigns issue to both of us.

After doing changes I can add you as co-author,that'll show you've worked on the issue too.

**Comment by soravkumarsharma** [comment]
Hello @ananya12k @Nalakajayanath, I assigned this issue to both of you.

**Comment by achilleasmitos** [comment]
Is this being actively worked on? If so, I would like to know what the progress is :) I would also be available to contribute to it if need be.

**Comment by soravkumarsharma** [comment]
I don't know they are working on this issue or not if you want to made some contribution or working on this issue then you can contribute it.

**Comment by achilleasmitos** [comment]
Thank you, but I'll refrain from doing so without their express agreement. Let's give them some time to answer.

Meanwhile, I can work on another issue, and perhaps drop some ideas of my own :)

**Comment by ananya12k** [comment]
@achilleasmitos  Go ahead if you want to contribute to this issue
