### ISSUE TITLE
Codeowners

### ISSUE THREAD

**Issue by achilleasmitos** [soravkumarsharma/ATM-Project-for-Beginners#17]
**Is your feature request related to a problem? Please describe.**
As an open source project with different contributors, it might be a good idea to establish early on code owners for different parts of the repository, so that changes made to them have to reviewed by the code owners of those particular parts (this also requires an accompanying change in the PRs of the repo).

**Describe the solution you'd like**
Add a CODEOWNERS file as described [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) specifying the first code owners.

**Describe alternatives you've considered**
No alternative solution, as this is merely a suggestion based on personal experience and good practices.

**Additional context**
No additional context necessary.

**Comment by soravkumarsharma** [comment]
Hi Achilleas, I hope you are doing good, I'm adding you in the codeowners
file for the PR review.
