### ISSUE TITLE
Mask password with asterisk

### ISSUE THREAD

**Issue by soravkumarsharma** [soravkumarsharma/ATM-Project-for-Beginners#4]
masking is an important technique that is used vastly in programming for security purposes like logging in and signing up for entering any pin information.

**Comment by Rishav1707** [comment]
I would like to work on this issue, but I can't remember how to do that.
Maybe some `cout` function is used to mask passwords with an asterisk.

**Comment by soravkumarsharma** [comment]
you can do this with many ways

**Comment by Rishav1707** [comment]
> you can do this with many ways

Can you help me to do this?

**Comment by soravkumarsharma** [comment]
you can use getch() function which is a predefined non-standard function that is defined in conio.h header file. Using getch() function, you can hide the input character provided by the users in the ATM PIN, password, etc.

**Comment by Rishav1707** [comment]
> you can use getch() function which is a predefined non-standard function that is defined in conio.h header file. Using getch() function, you can hide the input character provided by the users in the ATM PIN, password, etc.

Ok I'll report to you soon...

**Comment by soravkumarsharma** [comment]
okay buddy!!
