### ISSUE TITLE
Add "Bank Statement" Option.

### ISSUE THREAD

**Issue by soravkumarsharma** [soravkumarsharma/ATM-Project-for-Beginners#6]
A bank statement is an official document that summarizes your account activity over a certain period of time—typically one month. You’ll find records of all transactions—both incoming and outgoing.

**Comment by Arman49** [comment]
Hello sir. I am new to open source. I just forked an Issue in this project. But after that, I'm perplexed. I couldn't find anything to contribute. Please help me.

**Comment by achilleasmitos** [comment]
@soravkumarsharma could you please assign this issue to me? Thank you in advance :)
