### ISSUE TITLE
[Bug] Logout functionality not working

### ISSUE THREAD

**Issue by CoderYuvi** [soravkumarsharma/ATM-Project-for-Beginners#7]
While choosing option 5 which is for Logging out the code is not logging out the user and instead displaying the same set of options which were asked to the logged user.

### **Steps to recreate the scenario:**
Step 1: Fill the initial details and create the account.
Step 2: Press 5 on keyboard to Logout.
Step 3: Enter your email id and 4-digit pin.
Step 4: You will again see the Welcome Page. 

### **Screenshot:**
![logout issue](https://github.com/soravkumarsharma/ATM-Project-for-Beginners/assets/84584971/d751ab07-b57d-4a74-8672-096ea2df8831)

**Comment by ananya12k** [comment]
Can you assign me this issue? 
I would like to work on this.

**Comment by soravkumarsharma** [comment]
Yes sure

**Comment by soravkumarsharma** [comment]
> Can you assign me this issue? I would like to work on this.

Assigned

**Comment by ananya12k** [comment]
It is not a bug the problem is already solved.
After pressing 5 on keyboard, console clears and login screen comes up, it is not showing same options shown to logged user, if the problem is solved the issue can be closed.
Correct me if I am wrong.
